#!/bin/sh

### varibles ###

PANEL_HEIGHT=16
PANEL_FIFO="/tmp/panel-fifo"
PANEL_FONT="Fira Code:size=9"

appendpath()
{
    case ":$PATH:" in
        *:"$1":*)
        ;;
        *)
        PATH="${PATH:+$PATH:}$1"
    esac
}

export EDITOR=vim
export GOPATH="$HOME/.go"
export LANG="en_GB.UTF-8"
appendpath /usr/local/bin
appendpath $GOPATH/bin

### settings ###

bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config border_radius 20
bspc config window_gap 10
bspc config top_padding 18

bspc config focused_border_color \#5e81ac
bspc config normal_border_color \#3b4252

### auto-start ###

xsetroot -cursor_name arrow &
xrdb .Xresources &
picom -b --experimental-backends --vsync &
setxkbmap gb &
setxkbmap -option caps:escape &
sxhkd > ~/.cache/sxhkd.log &
xset -b -r &
hsetroot -center "$("$HOME"/.config/bspwm/rand_file.sh "$HOME"/pics/wallpapers/)" &
clipmenud &
mocp -S &
mocp --on shuffle &

dunst &
bspswallow &
unclutter &

### panel ###

bspwmbar &
